# -*- coding: utf-8 -*-
#################################################################################
# Author      : Acespritech Solutions Pvt. Ltd. (<www.acespritech.com>)
# Copyright(c): 2012-Present Acespritech Solutions Pvt. Ltd.
# All Rights Reserved.
#
# This program is copyright property of the author mentioned above.
# You can`t redistribute it and/or modify it.
#
#################################################################################

{
    'name': 'POS Restaurant (Enterprise)',
    'version': '3.0.0',
    'category': 'Point of Sale',
    'website': 'http://www.acespritech.com',
    'price': 900.0,
    'currency': 'EUR',
    'summary': "POS Restaurant with BOM, Combo, Kitchen Screen.",
    'description': """
        POS Restaurant with BOM, Combo, Kitchen Screen, Customer Screen
    """,
    'author': "Acespritech Solutions Pvt. Ltd.",
    'depends': ['base', 'mrp', 'point_of_sale', 'bus', 'pos_restaurant', 'pos_hr', 'purchase'],
    'data': [
        'security/ir.model.access.csv',
        'security/monitor_security.xml',
        'data/order_type.xml',
        'data/product_data.xml',
        'data/mail_template.xml',
        'views/wallet_management_view.xml',
        'views/pos_payment_method_view.xml',
        'views/pos_assets_common.xml',
        'views/mrp_bom_view.xml',
        'views/combo_view.xml',
        'views/res_users_view.xml',
        'views/pos_config_view.xml',
        'views/res_partner_view.xml',
        'views/gift_card.xml',
        'views/gift_voucher_view.xml',
        'views/res_config_setting.xml',
        'views/hr_employee_view.xml',
        'report/pos_z_report_template.xml',
        'report/pos_z_thermal_report.xml',
        'report/front_sales_thermal_report_template.xml',
        'report/front_sales_report_pdf_template.xml',
        'report/front_inventory_session_thermal_report_template.xml',
        'report/front_inventory_session_pdf_report_template.xml',
        'report/front_inventory_location_thermal_report_template.xml',
        'report/front_inventory_location_pdf_report_template.xml',
        'report/report.xml',
        'views/pos_order_view.xml',
        'views/pos_session_view.xml',
        'views/pos_product_view.xml',
        'views/pos_delivery_service_view.xml',
        'views/remove_product_resion_view.xml',
    ],
    'images': ['static/description/flexibite_screen_main.png'],
    'qweb': [
        'static/src/xml/Chrome.xml',
        'static/src/xml/Screens/ProductScreen/Orderline.xml',
        'static/src/xml/Screens/ProductScreen/ActionpadWidget.xml',
        'static/src/xml/ChromeWidgets/KitchenScreenButton.xml',
        'static/src/xml/Screens/ReceiptScreen/OrderReceipt.xml',

        'static/src/xml/Popups/ProductConfiguratorPopup.xml',
        'static/src/xml/Popups/MaterialReplacePopup.xml',
        'static/src/xml/Popups/ComboReplacePopup.xml',
        'static/src/xml/Popups/MaterialInfoPopup.xml',
        'static/src/xml/Popups/SplitCombolinePopup.xml',
        'static/src/xml/Popups/MergeCombolinePopup.xml',
        'static/src/xml/Popups/ComboInfoPopup.xml',
        'static/src/xml/Popups/KitchenOrderCardPopup.xml',

        'static/src/xml/Screens/CustomOrderScreen/CustomOrderScreen.xml',
        'static/src/xml/Screens/CustomOrderScreen/MaterialWidget.xml',
        'static/src/xml/Screens/CustomOrderScreen/Materialline.xml',
        'static/src/xml/Screens/CustomOrderScreen/MaterialSummery.xml',
        'static/src/xml/Screens/CustomOrderScreen/MaterialpadWidget.xml',
        'static/src/xml/Screens/CustomOrderScreen/ReplaceProductWidget.xml',
        'static/src/xml/Screens/CustomOrderScreen/BomCategoryButton.xml',
        'static/src/xml/Screens/CustomOrderScreen/ReplaceProductItemS.xml',
        'static/src/xml/Screens/CustomOrderScreen/ReplaceBOMWidgetControlPanel.xml',

        'static/src/xml/Screens/ComboScreen/CreateComboScreen.xml',
        'static/src/xml/Screens/ComboScreen/ComboWidget.xml',
        'static/src/xml/Screens/ComboScreen/Comboline.xml',
        'static/src/xml/Screens/ComboScreen/CombopadWidget.xml',
        'static/src/xml/Screens/ComboScreen/ComboSummery.xml',
        'static/src/xml/Screens/ComboScreen/ComboProductsWidget.xml',
        'static/src/xml/Screens/ComboScreen/ComboProductsWidgetControlPanel.xml',
        'static/src/xml/Screens/ComboScreen/ComboCategoryButton.xml',
        'static/src/xml/Screens/ComboScreen/ComboProductList.xml',
        'static/src/xml/Screens/ComboScreen/ComboProductItem.xml',

        'static/src/xml/Screens/ComboCustomiseProductScreen/ComboCustomiseProductScreen.xml',
        'static/src/xml/Screens/ComboCustomiseProductScreen/ComboMaterialline.xml',
        'static/src/xml/Screens/ComboCustomiseProductScreen/ComboMaterialpadWidget.xml',
        'static/src/xml/Screens/ComboCustomiseProductScreen/ComboMaterialSummery.xml',
        'static/src/xml/Screens/ComboCustomiseProductScreen/ComboMaterialWidget.xml',
        'static/src/xml/Screens/ComboCustomiseProductScreen/ComboReplaceProductWidget.xml',
        'static/src/xml/Screens/ComboCustomiseProductScreen/ComboReplaceProductItemS.xml',

        'static/src/xml/Screens/KitchenScreen/KitchenScreen.xml',
        'static/src/xml/Screens/KitchenScreen/OrderCard.xml',
        'static/src/xml/Screens/KitchenScreen/GridOrderCard.xml',
        'static/src/xml/Screens/KitchenScreen/OrderCardLine.xml',
        'static/src/xml/Screens/KitchenScreen/MaterialCardLine.xml',
        'static/src/xml/Screens/KitchenScreen/FilterSwitch.xml',
        'static/src/xml/Screens/KitchenScreen/StatisticBox.xml',
        'static/src/xml/Screens/KitchenScreen/OrderLinePrint.xml',
        'static/src/xml/Screens/KitchenScreen/OrderPrint.xml',

        'static/src/xml/CustomerDisplay.xml',
        'static/src/xml/ChromeWidgets/CustomerScreenButton.xml',
        'static/src/xml/CustomerDisplayWidgets/RightWidget.xml',
        'static/src/xml/CustomerDisplayWidgets/LeftWidget.xml',
        'static/src/xml/CustomerDisplayWidgets/CustomerOrderline.xml',
        'static/src/xml/CustomerDisplayWidgets/VideoSlider.xml',
        'static/src/xml/CustomerDisplayWidgets/Ratings.xml',
        'static/src/xml/CustomerDisplayWidgets/PaymentDetail.xml',
        'static/src/xml/CustomerDisplayWidgets/PaymentLines.xml',
        'static/src/xml/CustomerDisplayWidgets/Slider/Slider.xml',
        'static/src/xml/CustomerDisplayWidgets/Slider/SliderContent.xml',
        'static/src/xml/CustomerDisplayWidgets/Slider/Slide.xml',
        'static/src/xml/CustomerDisplayWidgets/Slider/Arrow.xml',
        'static/src/xml/Popups/CustomerFeedbackPopup.xml',
        'static/src/xml/Popups/CustomerCreatePopup.xml',

        'static/src/xml/Screens/PaymentScreen/PaymentScreen.xml',
        'static/src/xml/Popups/Wallet/PaymentWalletPopup.xml',
        'static/src/xml/Popups/Wallet/WalletPopup.xml',
        'static/src/xml/Screens/ProductScreen/PosProductScreen.xml',
        'static/src/xml/Screens/ProductScreen/CustomControlButtons/MiddelCustomControlButton.xml',

        'static/src/xml/Popups/GiftCard/giftCardCreatePopup.xml',
        'static/src/xml/Popups/GiftCard/giftCardCreatePopupConform.xml',
        'static/src/xml/Popups/GiftCard/giftCardEditExpirePopup.xml',
        'static/src/xml/Popups/GiftCard/giftCardExchangePopup.xml',
        'static/src/xml/Popups/GiftCard/giftCardRechargePopup.xml',
        'static/src/xml/Popups/GiftCard/giftCardRedeemPopup.xml',
        'static/src/xml/Screens/GiftCardScreen/giftCardCreateScreen.xml',
        'static/src/xml/Screens/GiftCardScreen/GiftCardLine.xml',
        'static/src/xml/Screens/GiftCardScreen/GiftCardScreen.xml',

        'static/src/xml/Popups/GiftVoucher/giftVoucherRedeemPopup.xml',
        'static/src/xml/Screens/GiftVoucherScreen/GiftVoucherHistoryLine.xml',
        'static/src/xml/Screens/GiftVoucherScreen/GiftVoucherLine.xml',
        'static/src/xml/Screens/GiftVoucherScreen/GiftVoucherScreen.xml',
        'static/src/xml/Screens/GiftVoucherScreen/ControlButtons/giftVoucherControlButton.xml',
        'static/src/xml/Popups/MoneyInOut/MoneyInOutPopup.xml',
        'static/src/xml/Screens/ReceiptScreen/ReceiptScreen.xml',
        'static/src/xml/Screens/ReceiptScreen/MoneyInOutReceipt.xml',
        'static/src/xml/Screens/LoginScreen/LoginScreen.xml',
        'static/src/xml/Screens/ProductScreen/ProductList.xml',
        'static/src/xml/Screens/ProductScreen/ProductsWidget.xml',
        'static/src/xml/Screens/ProductScreen/ProductsWidgetControlPanel.xml',
        'static/src/xml/Screens/ProductScreen/VerticalProductCategory.xml',
        'static/src/xml/ChromeWidgets/LockPosScreen.xml',
        'static/src/xml/ChromeWidgets/UnlockPosScreen.xml',
        'static/src/xml/Screens/CashControlScreen/CashControlScreen.xml',
        'static/src/xml/Screens/CashControlScreen/CashControlScreenInput.xml',
        'static/src/xml/Screens/CashControlScreen/StaticInputLines.xml',
        'static/src/xml/Screens/CloseCashControlScreen/CloseCashControlScreen.xml',
        'static/src/xml/Screens/CloseCashControlScreen/CloseCashControlScreenInput.xml',
        'static/src/xml/Popups/CloseSession/CloseSessionPopup.xml',
        'static/src/xml/Screens/OrderReturnScreen/OrderReturnProductList.xml',
        'static/src/xml/ChromeWidgets/OpenDetailButton.xml',
        'static/src/xml/Screens/OrderReturnScreen/OrderReturnScreen.xml',
        'static/src/xml/ChromeWidgets/BiteDetailSidebar.xml',
        'static/src/xml/Screens/ProductScreen/ProductDetailScreen.xml',
        'static/src/xml/Popups/ProductDetail/PurchaseOrderCreate.xml',

        'static/src/xml/Popups/Reports/AuditReportPopup.xml',
        'static/src/xml/Popups/Reports/OrderSummaryPopup.xml',
        'static/src/xml/Popups/Reports/PaymentSummaryPopup.xml',
        'static/src/xml/Popups/Reports/ProductSummaryPopup.xml',

        'static/src/xml/Screens/ReceiptScreen/OrderSummaryReceipt.xml',
        'static/src/xml/Screens/ReceiptScreen/PaymentSummaryReceipt.xml',
        'static/src/xml/Screens/ReceiptScreen/ProductSummaryReceipt.xml',
        'static/src/xml/Screens/ProductScreen/ControlButtons/SendToKitchenButton.xml',
        'static/src/xml/Screens/ReceiptScreen/TokenReceipt.xml',

        'static/src/xml/Screens/MaterialMonitorScreen/MateriaItem.xml',
        'static/src/xml/Screens/MaterialMonitorScreen/MaterialList.xml',
        'static/src/xml/Screens/MaterialMonitorScreen/MaterialMonitorControlPanel.xml',
        'static/src/xml/Screens/MaterialMonitorScreen/MaterialMonitordetail.xml',
        'static/src/xml/Screens/MaterialMonitorScreen/MaterialMonitorScreen.xml',
        'static/src/xml/Popups/delivery_service/DeliveryServicePopup.xml',
        'static/src/xml/Popups/delivery_service/DeliveryServiceLinePopup.xml',
        'static/src/xml/Screens/PaymentScreen/PaymentScreendisabledNumpad.xml',
        'static/src/xml/Screens/SyncPosOrderScreen/SyncOrderDetails.xml',
        'static/src/xml/Screens/SyncPosOrderScreen/SyncOrderlineDetails.xml',
        'static/src/xml/Screens/SyncPosOrderScreen/SyncOrderScreen.xml',
        'static/src/xml/ChromeWidgets/OrderSyncScreenButton.xml',

    ],
    'installable': True,
    'auto_install': False
}
# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
